/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica.del.proyecto;

import proyecto.Repuestos;

/**
 *
 * @author AZUAJE
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Respuestos = new javax.swing.JButton();
        Servicio = new javax.swing.JButton();
        Catalogo = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        repuestos = new javax.swing.JLabel();
        servicios = new javax.swing.JLabel();
        ayuda = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agencia de Bicicletas: La Llegada");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Respuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/del/proyecto/Imagenes/set-icons-bicycle-biking-bike-parts-equipment-isolated-white-39698579.jpg"))); // NOI18N
        Respuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespuestosActionPerformed(evt);
            }
        });
        getContentPane().add(Respuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, 140));

        Servicio.setForeground(new java.awt.Color(255, 255, 255));
        Servicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/del/proyecto/Imagenes/can-stock-photo_csp38868715.jpg"))); // NOI18N
        getContentPane().add(Servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 150, 140));

        Catalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/del/proyecto/Imagenes/reparacion.jpg"))); // NOI18N
        Catalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(Catalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 140, 150));

        Salir.setBackground(new java.awt.Color(255, 255, 255));
        Salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 0, 0));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/del/proyecto/Imagenes/Error.png"))); // NOI18N
        Salir.setText("Cerrar Sesion");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, 30));

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("AGENCIA DE BICICLETAS");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("\"LA LLEGADA\"");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        repuestos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        repuestos.setForeground(new java.awt.Color(255, 255, 255));
        repuestos.setText("Respuestos");
        getContentPane().add(repuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        servicios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        servicios.setForeground(new java.awt.Color(255, 255, 255));
        servicios.setText("Servicios");
        getContentPane().add(servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        ayuda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ayuda.setForeground(new java.awt.Color(255, 255, 255));
        ayuda.setText("Arma tu Bicicleta");
        getContentPane().add(ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        fondo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/del/proyecto/Imagenes/241688__astana-bike-astana-kazakhstan-cycling-the-best-team-claude-kloden_p.jpg"))); // NOI18N
        fondo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 778, 500));

        jMenu1.setText("Archivo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Imagenes/File_List.png"))); // NOI18N
        jMenuItem1.setText("Lista de Precios");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Imagenes/Paste.png"))); // NOI18N
        jMenuItem2.setText("Lista de Repuestos");
        jMenu1.add(jMenuItem2);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Imagenes/Pencil_2.png"))); // NOI18N
        jMenu5.setText("Editar datos");

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Imagenes/dollar_sign.png"))); // NOI18N
        jMenuItem12.setText("Precios");
        jMenu5.add(jMenuItem12);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Imagenes/tools.png"))); // NOI18N
        jMenuItem13.setText("Servicios");
        jMenu5.add(jMenuItem13);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Reportes");

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Imagenes/File_Edit.png"))); // NOI18N
        jMenuItem8.setText("Diario");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Imagenes/File_List.png"))); // NOI18N
        jMenuItem9.setText("Semanal");
        jMenu4.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Imagenes/Book.png"))); // NOI18N
        jMenuItem10.setText("Mensuales");
        jMenu4.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Imagenes/Bookmark.png"))); // NOI18N
        jMenuItem11.setText("Anuales");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Registro");

        jMenuItem3.setText("Repuestos");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Servicios");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Proveedores");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Imagenes/Help.png"))); // NOI18N
        jMenuItem6.setText("Ver la ayuda");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Imagenes/Info.png"))); // NOI18N
        jMenuItem7.setText("Acerca de..!");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RespuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespuestosActionPerformed
       Repuestos objeto = new Repuestos();
       objeto.setVisible(true);
       dispose();
    }//GEN-LAST:event_RespuestosActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void CatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatalogoActionPerformed
        Servicios objeto = new Servicios();
        objeto.setVisible(true);
        dispose();
    }//GEN-LAST:event_CatalogoActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        Login objeto = new Login();
        objeto.setVisible(true);
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Catalogo;
    private javax.swing.JButton Respuestos;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Servicio;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel ayuda;
    private javax.swing.JLabel fondo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel repuestos;
    private javax.swing.JLabel servicios;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
