/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica.del.proyecto;

import javax.swing.JOptionPane;
import proyecto.RecuperarContraseña;

/**
 *
 * @author AZUAJE
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        Instrucciones = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Pass = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JPasswordField();
        recuperar_clave = new javax.swing.JLabel();
        btn_acceder = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agencia de Bicicletas: La Llegada");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("AGENCIA DE BICICLETAS");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("\"LA LLEGADA\"");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        Instrucciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Instrucciones.setForeground(new java.awt.Color(255, 255, 255));
        Instrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/del/proyecto/Imagenes/user-icon-512 - copia - copia.png"))); // NOI18N
        Instrucciones.setText("Ingrese el Usuario y la Contraseña para ingresar al sistema");
        getContentPane().add(Instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        User.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setText("USUARIO:");
        getContentPane().add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        Pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Pass.setForeground(new java.awt.Color(255, 255, 255));
        Pass.setText("CONTRASEÑA:");
        getContentPane().add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 190, -1));
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 190, -1));

        recuperar_clave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        recuperar_clave.setForeground(new java.awt.Color(255, 255, 255));
        recuperar_clave.setText("¿Olvido su contraseña?");
        recuperar_clave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recuperar_claveMouseClicked(evt);
            }
        });
        getContentPane().add(recuperar_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        btn_acceder.setBackground(new java.awt.Color(255, 255, 255));
        btn_acceder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_acceder.setForeground(new java.awt.Color(102, 153, 0));
        btn_acceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/del/proyecto/Imagenes/Valid.png"))); // NOI18N
        btn_acceder.setText("Acceder");
        btn_acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accederActionPerformed(evt);
            }
        });
        getContentPane().add(btn_acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, -1, 30));

        btn_salir.setBackground(new java.awt.Color(255, 255, 255));
        btn_salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 0, 0));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/del/proyecto/Imagenes/Error.png"))); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/del/proyecto/Imagenes/241688__astana-bike-astana-kazakhstan-cycling-the-best-team-claude-kloden_p.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 778, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accederActionPerformed
        String Usuario= "administrador";
        String Clave= "23458";
        
        String pass=new String(contraseña.getPassword());
        String user=new String(usuario.getText());
        
        if(user.equals(Usuario) && pass.equals(Clave)){
            
            Inicio acc= new Inicio();
            acc.setVisible(true);
            dispose();
            
        }else{
            JOptionPane.showMessageDialog(this, "El usuario y/o la Contraseña son incorrectos");
        }
    }//GEN-LAST:event_btn_accederActionPerformed

    private void recuperar_claveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recuperar_claveMouseClicked
        RecuperarContraseña objeto = new RecuperarContraseña();
        objeto.setVisible(true);
        dispose();
    }//GEN-LAST:event_recuperar_claveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Instrucciones;
    private javax.swing.JLabel Pass;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel User;
    private javax.swing.JButton btn_acceder;
    private javax.swing.JButton btn_salir;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel recuperar_clave;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
